jiwen_banner_banner:
    resource: "@JiwenBannerBundle/Resources/config/routing/banner.yml"
    prefix:   /administration/banner

jiwen_banner_top:
    pattern: /banner_top
    defaults: { _controller: "JiwenBannerBundle:Banner:topBanner" }