jiwen_alipay_homepage:
    pattern:  /account/alipay/{order_id}
    defaults: { _controller: JiwenAlipayBundle:Alipay:index }

alipay_notify:
    pattern:  /notify
    defaults: { _controller: JiwenAlipayBundle:Alipay:notify }

alipay_return:
    pattern:  /return
    defaults: { _controller: JiwenAlipayBundle:Alipay:return }