parameters:
#    jiwen_alipay.example.class: Jiwen\AlipayBundle\Example

services:
#    jiwen_alipay.example:
#        class: %jiwen_alipay.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
