jiwen_comment:
    resource: "@JiwenCommentBundle/Resources/config/routing.yml"
    prefix:   /

jiwen_general:
    resource: "@JiwenGeneralBundle/Resources/config/routing.yml"
    prefix:   /

jiwen_banner:
    resource: "@JiwenBannerBundle/Resources/config/routing.yml"
    prefix:   /

JiwenBannerBundle_bannercategory:
        resource: "@JiwenBannerBundle/Resources/config/routing/bannercategory.yml"
        prefix:   /administration/bannercategory

sylius_installer:
    resource: @SyliusInstallerBundle/Resources/config/routing.yml

sylius_web:
    resource: @SyliusWebBundle/Resources/config/routing/main.yml

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /account/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /account
