jiwen_bookmark_homepage:
    pattern: /
    methods: [GET]
    defaults:
        _controller: jiwen.controller.bookmark:indexAction

jiwen_bookmark_create:
    pattern: /new
    methods: [GET, PUT, POST]
    defaults:
        _controller: jiwen.controller.bookmark:createAction
        _sylius:
            form: jiwen_bookmark