jiwen_bookmark_homepage:
    pattern:  /
    defaults: { _controller: JiwenBookmarkBundle:Bookmark:index }
bookmark:
    pattern:  /
    defaults: { _controller: JiwenBookmarkBundle:Bookmark:index }

bookmark_new:
    pattern:  /new
    defaults: { _controller: JiwenBookmarkBundle:Bookmark:new }

bookmark_create:
    pattern:  /create
    defaults: { _controller: JiwenBookmarkBundle:Bookmark:create }

bookmark_edit:
    pattern:  /{id}/edit
    defaults: { _controller: JiwenBookmarkBundle:Bookmark:edit }

bookmark_show:
    pattern:  /{id}
    defaults: { _controller: JiwenBookmarkBundle:Bookmark:show }

bookmark_show:
    pattern:  /{id}
    defaults: { _controller: JiwenBookmarkBundle:Bookmark:show }

bookmark_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "JiwenBookmarkBundle:Bookmark:delete" }
    requirements: { _method: post|delete }

bookmark_update:
    pattern:  /{id}/update
    defaults: { _controller: "JiwenBookmarkBundle:Bookmark:update" }
    requirements: { _method: post|put }