parameters:
#    jiwen_bookmark.example.class: Jiwen\BookmarkBundle\Example

services:
#    jiwen_bookmark.example:
#        class: %jiwen_bookmark.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
